name: AnomalyEvent
version: 1.0.0
main: me.w1loz3r.anomaly.AnomalyEventPlugin
api-version: '1.21'
authors: [w1loz3r]
description: Rift/Anomaly event plugin with fog, storm and long night

commands:
  anomaly:
    description: Control anomaly event
    usage: |
      /anomaly on
      /anomaly off
      /anomaly status
      /anomaly fog <on|off|level 0-3>
      /anomaly storm <on|off>
      /anomaly night <on|off>
      /anomaly rift size <length> <halfWidthTop> <jagged>
      /anomaly rift rebuild
    permission: anomaly.admin

permissions:
  anomaly.admin:
    description: Full control of anomaly event
    default: op
